#!/bin/zsh
set -x;
export LANG='en_US.UTF-8';
cd '/home/athen/cnulug.org';
GIT_WORK_TREE=/home/athen/cnulug.org git checkout master -f
./dp build;
./site rebuild;
rm -rf /srv/http/cnulug.org/*;
cp -R _site/* /srv/http/cnulug.org/;
set +x;
